# InvokeAI initialization file
# This is the InvokeAI initialization file, which contains command-line default values.
# Feel free to edit. If anything goes wrong, you can re-initialize this file by deleting
# or renaming it and then running invokeai-configure again.

# The --root option below points to the folder in which InvokeAI stores its models, configs and outputs.
--root="/Users/mauwii/invokeai"

# the --outdir option controls the default location of image files.
--outdir="/Users/mauwii/invokeai/outputs"

# You may place other  frequently-used startup commands here, one or more per line.
# Examples:
--web
# --steps=20
# -Ak_euler_a -C10.0